const OPEN_MODAL = 'calendar/OPEN_MODAL';
const CLOSE_MODAL = 'calendar/CLOSE_MODAL';
const SET_SELECTED_EVENT = 'calendar/SET_SELECTED_EVENT';
const CLEAR_SELECTED_EVENT = 'calendar/CLEAR_SELECTED_EVENT';

export default {
	OPEN_MODAL,
	CLOSE_MODAL,
	SET_SELECTED_EVENT,
	CLEAR_SELECTED_EVENT
};
