const UPDATE_CURRENT_MESSAGE = 'messageBoard/UPDATE_CURRENT_MESSAGE';
const TOGGLE_MESSAGE_BOARD = 'messageBoard/TOGGLE_MESSAGE_BOARD';
const CLEAR_CURRENT_MESSAGE = 'messageBoard/CLEAR_CURRENT_MESSAGE';

export default {
	UPDATE_CURRENT_MESSAGE,
	TOGGLE_MESSAGE_BOARD,
	CLEAR_CURRENT_MESSAGE
};
