const SET_SAVE_STATE = 'userProfile/SET_SAVE_STATE';

const SET_EDIT_ICON_LINK = 'userProfile/SET_EDIT_ICON_LINK';

const SET_INITIAL_USER_DATA = 'userProfile/SET_INITIAL_USER_DATA';

const UPDATE_USER_DATA = 'userProfile/UPDATE_USER_DATA';

export default {
	SET_SAVE_STATE,
	SET_EDIT_ICON_LINK,
	SET_INITIAL_USER_DATA,
	UPDATE_USER_DATA
};
