const SET_ACTIVE_BUTTON = "admin/SET_ACTIVE_BUTTON";
const OPEN_MODAL = "admin/OPEN_MODAL";
const CLOSE_MODAL = "admin/CLOSE_MODAL";
const UPDATE_SEARCH_TERM = "admin/UPDATE_SEARCH_TERM";
const UPDATE_FIELD_VALUE = "admin/UPDATE_FIELD_VALUE";
const RESET_FIELDS = "admin/RESET_FIELDS";

export default {
  SET_ACTIVE_BUTTON,
  OPEN_MODAL,
  CLOSE_MODAL,
  UPDATE_SEARCH_TERM,
  UPDATE_FIELD_VALUE,
  RESET_FIELDS
};
