const REQUEST_SIGN_UP = 'signUp/REQUEST_SIGN_UP';
const SIGN_UP_SUCCESS = 'signUp/SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'login/SIGN_UP_FAILURE';
const HANDLE_SIGN_UP_CHANGE = 'login/HANDLE_SIGN_UP_CHANGE';

export default {
	REQUEST_SIGN_UP,
	SIGN_UP_SUCCESS,
	SIGN_UP_FAILURE,
	HANDLE_SIGN_UP_CHANGE
};
