const REQUEST_LOGIN = 'login/REQUEST_LOGIN';
const RECEIVE_LOGIN = 'login/RECEIVE_LOGIN';
const HANDLE_LOGIN_CHANGE = 'login/HANDLE_LOGIN_CHANGE';

export default {
	REQUEST_LOGIN,
	RECEIVE_LOGIN,
	HANDLE_LOGIN_CHANGE
};
