const REQUEST_LOGIN = 'login/REQUEST_LOGIN';
const LOGIN_SUCCESS = 'login/LOGIN_SUCCESS';
const LOGIN_FAILURE = 'login/LOGIN_FAILURE';
const HANDLE_LOGIN_CHANGE = 'login/HANDLE_LOGIN_CHANGE';

export default {
	REQUEST_LOGIN,
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	HANDLE_LOGIN_CHANGE
};
